services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webdev_container
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: company
    volumes:
      - .:/app
    ports:
      - 80:80  # Expose Python app
  
  mysql:
    image: mysql:latest
    container_name: webdev_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: company
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webdev_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80
      
volumes:
  mysql_data:
  arangodb_data: